import "./global.css"
import Footer from "@/app/_components/Footer"
import Navbar from "@/app/_components/Navbar"
import { AuthContextProvider } from "@/app/_context/AuthContext"
import { Open_Sans } from "next/font/google"

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
}

const inter = Open_Sans({
	subsets: ["latin"],
	display: "swap"
})

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" className={inter.className}>
			<AuthContextProvider>
				<body>
					<Navbar />
					<div className="App">{children}</div>
					<Footer />
				</body>
			</AuthContextProvider>
		</html>
	)
}
